### ISSUE TITLE
Clean installation not working

### ISSUE THREAD

**Issue by svenpool** [JC5/firefly-iii#229] opened 2016-03-23 15:21 UTC
Hi, 

I'm very curious about the firefly-iii program. So I created a VM, installed al the requirements and software needed. After a few attempts I finally got this far, but now I'm stuck. I hope you can help me out. After the command 'composer install' the scripts fails with the following message;

```
[root@finance firefly-iii]# composer install
> php artisan clear-compiled
PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
Stack trace:
#0 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): ReflectionClass->__construct('log')
#1 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('log', Array)
#2 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(687): Illuminate\Container\Container->make('log', Array)
#3 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(853): Illuminate\Foundation\Application->make('log')
#4 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(808): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(777): Il in /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 738
Script php artisan clear-compiled handling the pre-update-cmd event returned with an error


  [RuntimeException]
  Error Output: PHP Fatal error:  Uncaught ReflectionException: Class log does not exist in /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
  Stack trace:
  #0 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): ReflectionClass->__construct('log')
  #1 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('log', Array)
  #2 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(687): Illuminate\Container\Container->make('log', Array)
  #3 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(853): Illuminate\Foundation\Application->make('log')
  #4 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(808): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
  #5 /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php(777): Il in /var/www/html/firefly-iii/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 738


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
```
I've tried a git pull, perhaps I was missing files. I even deleted the previous git clone and started over, but I got the same message. 

Looking forward to hear from you. 

Regards,
Sven

**Comment by JC5** [comment] 2016-03-23 16:40
Hi! I'm back from holiday on Tuesday and will look into it!

**Comment by JC5** [comment] 2016-03-28 17:25
What does ``php -v`` say?

**Comment by svenpool** [comment] 2016-03-28 17:46
```
[root@finance ~]# php -v
PHP 7.0.4 (cli) (built: Mar  5 2016 01:22:48) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

```

**Comment by JC5** [comment] 2016-03-29 05:30
Alright, this is strange. I can't seem to reproduce your problem. Try the following:

``rm -rf vendor/ composer.lock``
``composer update --no-dev --no-scripts``
``composer update --no-dev``

**Comment by svenpool** [comment] 2016-03-29 08:21
Tried the commands, but I get the same error message.

I will delete the firefly-iii directory and try a fresh installation. 

Could it be that I'm missing a PHP plugin?

**Comment by JC5** [comment] 2016-03-29 09:26
Possibly, but I am not sure which one it would be.

**Comment by svenpool** [comment] 2016-03-29 13:31
Hi, 

Perhaps voor your installation page, if you try to install on CentOS.
```
#For the latest PHP7 version: 
rpm -Uvh https://mirror.webtatic.com/yum/el6/latest.rpm
rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
#Install the programs needed
yum install apache mysql mysql-server php70w php70w-mbstring php70w-mcrypt php70w-bcmath php70w-gd php70w-intl
#Install composer
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
```

I've created a new VM (CentOS 6.5), installed apache, php7 (php 5.6 doesn't work) and composer. And again I stumble across the same error message. 

The command `composer install`, makes sure it downloads files but with the `php artisan` command it goes wrong.

**Comment by JC5** [comment] 2016-03-29 19:02
Could you try this?

``yum install php70w-pdo``

**Comment by JC5** [comment] 2016-03-30 06:07
There is a ``DB_CONNECTION`` in your ``.env`` file which is most likely ``mysql``. Find and install a ``php-pdo-mysql`` package (or something similar) and install that one. The error is caused by PHP not being able to connect (over PDO) to your ``DB_CONNECTION``.

If you have found the package, reply with the name and I'll expand the installation instructions.

**Comment by svenpool** [comment] 2016-03-30 09:15
The final plugin that was missing was `php70w-mysql.x86_64`; 

And i needed to allow mod_rewrite in the apache conf :) 

Thanks for you help! I really appreciate it.

**Comment by JC5** [comment] 2016-03-30 09:32
You're welcome! Thanks for tackling the CentOS installation. I'll expand the installation guide for future use.

I'm closing the issue, let me know if there's anything I can help with.

**Closed by JC5** 2016-03-30 09:32 UTC
