### ISSUE TITLE
Split transaction is not shown in category charts and reports

### ISSUE THREAD

**Issue by zjean** [JC5/firefly-iii#417] opened 2016-11-22 21:44 UTC
Please see the image for an example.
I created two transactions one split transaction with this category only on the line, not on the 'header'. (€100)
Another transaction with this category in the header.
The charts only show the latter transaction.

![image](https://cloud.githubusercontent.com/assets/441924/20543053/b979df0e-b104-11e6-86c9-94a757d970c3.png)

The category report doesn't show this transaction either
![image](https://cloud.githubusercontent.com/assets/441924/20543169/3a1fb71e-b105-11e6-927c-8cf215151ab5.png)

Is this intended behaviour?
I'm on master. I will create a develop environment soon, so I can test issues there first before logging them ;-)

**Comment by JC5** [comment] 2016-11-23 06:45
Both transactions should show. Internally the system is intended to combine this. 

I'm pretty sure the development environment has this problem as well. It's pretty rare that I have fixed bugs in it already, the time to release is quite short. 

Root cause could be a number of things, I'll report back to soon!

**Comment by JC5** [comment] 2016-11-24 07:41
Root cause is a bunch of methods that do summaries. They can't really
handle the split journal thing. I'll start rewriting!

**Comment by JC5** [comment] 2016-11-24 21:21
Could you verify if this is fixed in develop, when you have time?

**Comment by zjean** [comment] 2016-11-24 21:59
Yes I did. Works well :-) 👍 
One small thing: When I go to reports, and don't select an account, I get a 404. Is the account selection mandatory?

The url becomes something like this: domain.com/reports/category/20161101/20161130//11
Note the double slash.

**Comment by JC5** [comment] 2016-11-24 22:08
Good catch! It should return with a message instead.

**Closed** 2016-12-07 12:38 UTC
